### ISSUE TITLE
Some messages not found when running pytest as `python -m pytest` against mypy 0.971

### ISSUE THREAD

**Issue by mwchase** [davidfritzsche/pytest-mypy-testing#26]
I don't think this is enough information to be actionable, but I hope I'm wrong, and I need some feedback on where to look next.

My typing tests started failing under mypy 0.971; reverting to 0.961 fixed the issue. All of the failures took the form of an expected message not being present. I was unable to replicate this issue in a small test file, but if I moved that file into the test folder, it exhibited the issue, even if tested individually.

Things that make the issue go away:
- Invoking pytest with `pytest` instead of `python -m pytest`
- Downgrading mypy to 0.961
- Testing the same file in a different tree (?)

Things that don't make the issue go away:
- Collecting only a subset of test files

Of note, if I just collect the small test file, in the main tree (so I can hit the issue), then invoking `python -m pytest` (which hits the issue) completes in 0.05s pretty consistently, while invoking `pytest` (which does not) tends to take over 7s.

I was poking around trying to replicate things, and I can't see any significant difference in the output from `mypy.api.run` between versions.

I wish I had more to go on here, but that's what I've found so far.

**Comment by mwchase** [comment]
Update: from running `coverage run -m pytest`, I can confirm that the `mypy.api.run` call is being dispatched, but there's no output whatsoever. I'm trying to trace `mypy` now, but I'm not making much progress yet.

**Comment by mwchase** [comment]
This is a regression in mypy 0.971, see https://github.com/python/mypy/issues/13214. It is fixed on master, and I've just confirmed that installing mypy master branch fixes the issue.

**Comment by davidfritzsche** [comment]
@mwchase Thanks for figuring it out. I anyway took the opportunity and upgraded the testing in this repo to also test with mypy 0.971

**Comment by mwchase** [comment]
Basically, the cause was that MYPYPATH was, apparently, including the directory that I was running pytest from. When running pytest as a module, it can't *remove* the current directory from sys.path. And when I was running tests in another directory... I'm not sure what was happening there.

Point is, *something* about my setup was putting the current directory in both of those. While the sys.path seems pretty straightforward, I'm not sure what was happening with the MYPYPATH.
