### ISSUE TITLE
new release required for recent pytest release

### ISSUE THREAD

**Issue by tlambert03** [davidfritzsche/pytest-mypy-testing#35]
Seeing the following error in my CI tests: 
```
    File "/tmp/.tox/py310-macos/lib/python3.10/site-packages/pytest_mypy_testing/plugin.py", line 12, in <module>
      from py._path.local import LocalPath
  ModuleNotFoundError: No module named 'py._path'; 'py' is not a package
```

looks like the changes from https://github.com/davidfritzsche/pytest-mypy-testing/pull/27 would fix it.
any plans for a new version release?

thanks!

**Comment by davidfritzsche** [comment]
Thank you for reporting this issue. Should be solved with version 0.1.0: https://pypi.org/project/pytest-mypy-testing/0.1.0/
