### ISSUE TITLE
Support for Pytest 8

### ISSUE THREAD

**Issue by bfontaine** [davidfritzsche/pytest-mypy-testing#46]
Hello,
This project [requires Pytest 7](https://github.com/davidfritzsche/pytest-mypy-testing/blob/main/pyproject.toml#L33); is there any plan to support [Pytest 8](https://docs.pytest.org/en/stable/changelog.html#pytest-8-0-0-2024-01-27) as well?
Thanks.

**Comment by davidfritzsche** [comment]
@bfontaine Thanks for reporting the issue that the plugin did not report compatibility with pytest 8. This got fixed with version 0.1.2.

**Comment by bfontaine** [comment]
Thank you!
